import "./asset/styles/global.scss";

export const metadata = {
  title: "Test Live Streaming",
  description: "Generated by Frontend Junior",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
