import "./asset/styles/global.scss";

export const metadata = {
  title: "Test Live Streaming",
  description: "Generated by Frontend Junior",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
